cache:
    untracked: true

stages:
    - test

test:
    stage: test
    script:
      - php -v
      - rm -rf vendor
      - composer install -o
      - mv phpunit.example.xml phpunit.xml
      - phpunit --coverage-text --colors=never